export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_REQUEST_SUCCESS = 'PRODUCT_LIST_REQUEST_SUCCESS'
export const PRODUCT_LIST_REQUEST_FAIL = 'PRODUCT_LIST_REQUEST_FAIL'